# Generated by Django 3.0.6 on 2020-07-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0003_service_siteconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='display',
            field=models.BooleanField(default=False),
        ),
    ]
