# Generated by Django 3.0.6 on 2020-07-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0006_aboutus_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icont',
            field=models.CharField(default=' ', max_length=20),
        ),
    ]
