# Generated by Django 3.0.8 on 2020-08-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0008_auto_20200722_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='about_us',
            field=models.TextField(max_length=2000, verbose_name='About Us'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='our_firm',
            field=models.TextField(max_length=2000, verbose_name='Our Firm'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='resume',
            field=models.TextField(max_length=2000, verbose_name='Resume Of the Director'),
        ),
    ]
