name: Deploy to Heroku on PR

on:
  pull_request:
    branches:
      - use-poetry

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.3  # Choose your Python version

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: your-heroku-app-name
        run: |
          heroku login -i
          git remote add heroku https://git.heroku.com/$HEROKU_APP_NAME.git
          git push heroku main:main  # Adjust to your branch name
